name: Integration Test

on:
  pull_request:
    branches:
      - df
  push:
    branches:
      - df

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        eventstore: [5.0.2, 5.0.5, 5.0.6]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: ssl
        run: ./scripts/generate-ssl-cert.sh
      - name: eventstore start
        run: |
          docker run -d -p 7773:7773 -p 7779:7779 -p 2113:2113 \
            -e EVENTSTORE_MEM_DB=true \
            -e EVENTSTORE_RUN_PROJECTIONS=all \
            -e EVENTSTORE_STATS_PERIOD_SEC=3000 \
            -e EVENTSTORE_EXT_TCP_PORT=7773 \
            -e EVENTSTORE_EXT_SECURE_TCP_PORT=7779 \
            -e EVENTSTORE_CERTIFICATE_FILE=/ssl/domain.p12 \
            -v ${PWD}/ssl:/ssl eventstore/eventstore:release-${{ matrix.eventstore }}
      - name: Build with Maven
        run: mvn clean verify sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_LOGIN }}
      - name: Codecov
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

